with Ada.Text_IO; use Ada.Text_IO;
procedure Hello is
begin
  Put_Line("An Ode To Lady Lovelace");
  Put_Line("One night at my evening soirée,");
  Put_Line("While babbling about my bobbling Babbage machine");
  Put_Line("I was introduced to the daughter of the mad Byron.");
  Put_Line("The rest of Intelligencia asked can it play Doom?");
  Put_Line("But my Enchantress of Numbers she knew,");
  Put_Line("In my defense she asked; Why when it could play music?");
  Put_Line("Oh my sweet Ada, you really are the first programmer.");
end Hello;